<<<<<<< HEAD
# fly.toml app configuration file generated for estuda-mais-reboot-crimson-feather-7968 on 2025-01-23T23:22:45-03:00
=======
# fly.toml app configuration file generated for estuda-mais-reboot on 2025-01-23T13:55:37Z
>>>>>>> 3b78ae7efabf17a8b1bf829f317929f851e18721
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

<<<<<<< HEAD
app = 'estuda-mais-reboot-crimson-feather-7968'
=======
app = 'estuda-mais-reboot'
>>>>>>> 3b78ae7efabf17a8b1bf829f317929f851e18721
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
<<<<<<< HEAD
=======
  memory_mb = 1024
>>>>>>> 3b78ae7efabf17a8b1bf829f317929f851e18721
